# Generated by Django 4.2.11 on 2024-06-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_id', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('instructions', models.TextField()),
                ('open_ai_model', models.CharField(max_length=500)),
                ('tools', models.JSONField(default=list)),
            ],
        ),
    ]
