# Generated by Django 4.2.11 on 2024-06-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenAIService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaiassistant',
            name='name',
            field=models.CharField(choices=[('RESUME_ANALYST', 'Resume Analyst')], max_length=50),
        ),
    ]
