# Generated by Django 4.2.14 on 2024-09-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenAIService', '0003_chathistory_tool_prompttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='context_params',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
