# Generated by Django 4.2.15 on 2024-10-01 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DoubtSolving', '0001_initial'),
        ('OpenAIService', '0004_tool_context_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[('1', 'Course')])),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('source_path', models.CharField(max_length=255)),
                ('source_type', models.IntegerField(choices=[('1', 'Azure Blob'), ('2', 'Amazon S3'), ('3', 'Google Drive')])),
                ('index_path', models.CharField(blank=True, max_length=255)),
                ('sas_token', models.CharField(blank=True, max_length=255)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoubtSolving.course')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoubtSolving.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ContentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.IntegerField(choices=[('1', 'PDF'), ('2', 'YouTube Video')])),
                ('path', models.CharField(max_length=255)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoubtSolving.course')),
                ('knowledge_repository_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenAIService.knowledgerepository')),
            ],
        ),
    ]
